apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-read
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "watch", "list"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-read-bind
subjects:
- kind: ServiceAccount
  name: cluster
  namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-read
  apiGroup: rbac.authorization.k8s.io
